//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorLogModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.Applications = new HashSet<Application>();
            this.UsersAndApplications = new HashSet<UsersAndApplication>();
        }

        [Key]
        public int ProfileId { get; set; }
        [Required(ErrorMessage = "Please Enter your FirstName")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Enter your LastName")]
        public string LastName { get; set; }
        [Required]
        public bool IsAdmin { get; set; }
        [Required(ErrorMessage = "Please Enter your Email")]
        [EmailAddress, MaxLength(40)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter your Password")]
        [MinLength(8)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
        [Required]
        public bool IsActive { get; set; }
        [Required]
        public System.DateTime LastLoginDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAndApplication> UsersAndApplications { get; set; }
    }
}
